filter:
    excluded_paths: [vendor/*, src/Tests/*]
    paths: [src/*]

tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit -c phpunit.xml.dist --colors --verbose
    php_analyzer: true
    php_changetracking: true
    php_code_sniffer:
        config:
            standard: PSR2
    php_mess_detector: true
    php_pdepend: true
    php_sim: true

build:
    dependencies:
        before:
            - "sudo composer self-update"
        override:
            - "composer install --no-interaction --prefer-dist"
    tests:
        override:
            -
                command: 'phpunit -c phpunit.xml.dist --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
